url: "https://hp-base-theme.gbif-uat.org" # the base hostname & protocol for your site, e.g. http://example.com

siteMeasurements:
  enable: false

plausible:
  enabled: false
  domain: hp-base-theme.gbif-uat.org

graphqlEndpoint: "https://graphql.gbif-uat.org/graphql"
