url: "https://hp-base-theme.gbif-staging.org" # the base hostname & protocol for your site, e.g. http://example.com

siteMeasurements:
  enable: true

plausible:
  enabled: false
  domain: hp-base-theme.gbif-staging.org