# SITE SETTINGS
title: Base theme
description: A jekyll theme for GBIFs hosted portals
url: "https://hp-base-theme.gbif.org"   # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "/tecala"                    # Only required if your site is in a subdirectory e.g. https://username.github.io/sitename
                                        # which has url: "https://username.github.io" (no slash) and baseurl: "/sitename" (leading slash)
                                        # A baseurl affects internal links, see http://peterdesmet.github.io/petridish/about/#links

# SOCIAL PROFILES
email: info@gbif.org                    # Social icon in footer
twitter_username: gbif                  # Social icon in footer
github_username: gbif                   # Social icon in footer
# youtube_username: gbif                  # Social icon in footer
# facebook_username: gbif                 # Social icon in footer

# THEME SETTINGS (ALL OPTIONAL)

tweets_on_home: false                      # Show Twitter feed of twitter_username on homepage

# For use by the 'standardPrivacy' layout
privacy:
  name: GBIF
  domain: gbif.org
  contactEmail: info@gbif.org
  helpdeskEmail: helpdesk@gbif.org

# The text for the terms can be changed by adding translations for 'terms', 'acceptTerms' and 'rejectTerms' in `/_data/translations.yml`.
siteMeasurements:
  enable: true # When enabled there will be a popup asking the user for their consent. If they accept then the function "attachMeasurements" will be called. You can overwrite this function by adding a file `/_includes/js/measure.js` and replace the function.
  GA_ID: "G-1FTDHGKVH0" # Your Google analytics ID. Sometimes they start with UA-XXXXX-X other times with G-XXXXXXXX depending on how you set it up
  termsVersion: "2021-07-06" # A version number for your terms. If you change this, then the users will see the popup again asking them to confirm/reject anew.

algae:
  rootLang: en
  # logo: /assets/img/tecala_logo.png     # Logo in navbar, will be displayed with 28px height
  logoAndTitle: false
  hideHelper: false
  archive_permalink: /posts/             # Permalink of page using archive.html layout, required when using post categories
  latestPostLimit: 3                    # Show x number of latest posts when showing latest posts. Defaults to 3
  style:
    square: true
    colors:
      primary: "#4787fb"
      links: "#4787fb"
    coloredHeadlineLinks: false
  navbar:
    # brandBackground: yellow
    # floating: true
    # color: "#00000088"
    # hasWhiteText: true

# BUILD SETTINGS
markdown: kramdown
plugins:                                # If you build your site on gh-pages, only use these plugins: https://pages.github.com/versions/
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-thumbor
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package-lock.json
  - package.json
  - jekyll-theme-algae.gemspec

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  ext: asciidoc 
  
# FRONTMATTER DEFAULTS
defaults:
  -
    scope:
      path: ""
    values:
      lang: en
  -
    scope:
      path: "la"
    values:
      lang: la
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/post/:year/:slug/"   # Use /post/yyyy/{filename}/ as permalink for all posts
      layout: "post"
  -
    scope:
      path: "_posts/la"
      type: "posts"
    values:
      permalink: "la/post/:year/:slug/"   # Use /post/yyyy/{filename}/ as permalink for all posts
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "page"                 # Only required for the theme website, implied for sites using a theme
